# Generated by Django 5.2 on 2026-07-19 08:29

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_datemodel_day_alter_datemodel_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemodel",
            name="file",
            field=models.FileField(
                upload_to=store.models.file_directory_path, verbose_name="فایل"
            ),
        ),
    ]
