# Generated by Django 5.2 on 2026-07-26 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_filemodel_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salemodel',
            options={'ordering': ['-date', 'customer'], 'verbose_name': 'فروش', 'verbose_name_plural': 'فروش\u200cها'},
        ),
        migrations.AlterUniqueTogether(
            name='salemodel',
            unique_together={('date', 'customer', 'product', 'count')},
        ),
    ]
