# Generated by Django 5.2 on 2026-07-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_salemodel_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="salemodel",
            unique_together={("date", "customer", "product", "count", "price")},
        ),
    ]
